# B2: Python 批量插入（输出）
+ 以下输出示例来自 `TiUP Playground`。
+ 如果客户端和 TiDB Cloud 不在同一个 region, 则两次执行之间的 `elapsed time` 差距会很大。
  + 如果你等不及第二个非批量样式演示运行完成, 请使用 `ctrl-c`。
```8
$ ./10-demo-python-batch-insert-01-show.sh ~!@local@!~
...
Connected to TiDB: root@127.0.0.1:4000
~!@Batch Inserting 10000 rows in 104.645751953125 (ms).@!~
Total rows in t1_batchtest table: 10000.
~!@Non-Batch Inserting 10000 rows in 5803.891845703125 (ms).@!~
Total rows in t1_batchtest table: 10000.
```
----------------------------------------------------------------
注意:

如果客户端和 TiDB Cloud 不在同一个 region, 以极端例子为例: 在 us-west-2 中对照 TiDB Cloud 在上海的一个节点上运行了演示脚本, 则引发了 DatabaseError 8229:

```
$ ./10-demo-python-batch-insert-01-show.sh cloud
Requirement already satisfied: mysql-connector in /opt/anaconda3/envs/flash/lib/python3.9/site-packages (from -r ./misc/requirements-dt.txt (line 2)) (2.2.9)
Requirement already satisfied: mysql-connector-python in /opt/anaconda3/envs/flash/lib/python3.9/site-packages (from -r ./misc/requirements-dt.txt (line 3)) (8.0.30)
Requirement already satisfied: protobuf<=3.20.1,>=3.11.0 in /opt/anaconda3/envs/flash/lib/python3.9/site-packages (from mysql-connector-python->-r ./misc/requirements-dt.txt (line 3)) (3.20.1)
Connected to TiDB: 2vWTTEGLyoDNK7K.root@gateway01.us-west-2.prod.aws.tidbcloud.com:4000
Batch Inserting 10000 rows in 1853.421142578125 (ms).
Total rows in t1_batchtest table: 10000.
Traceback (most recent call last):
  File "/Users/guanglei/git/github/tidb-course-201-lab/scripts/demo-batch-insert.py", line 83, in <module>
    _non_batch_style_insert(cursor, 10000)
  File "/Users/guanglei/git/github/tidb-course-201-lab/scripts/demo-batch-insert.py", line 30, in _non_batch_style_insert
    cursor.execute(sql_insert, (r,))
  File "/opt/anaconda3/envs/flash/lib/python3.9/site-packages/mysql/connector/cursor.py", line 1267, in execute
    res = self._connection.cmd_stmt_execute(
  File "/opt/anaconda3/envs/flash/lib/python3.9/site-packages/mysql/connector/connection.py", line 1549, in cmd_stmt_execute
    result = self._handle_binary_result(packet)
  File "/opt/anaconda3/envs/flash/lib/python3.9/site-packages/mysql/connector/connection.py", line 1448, in _handle_binary_result
    raise get_exception(packet)
mysql.connector.errors.DatabaseError: 8229 (HY000): TTL manager has timed out, pessimistic locks may expire, please commit or rollback this transaction
```